simulation_name = "main"

[meta]
[meta.unit_system_conversion]
from_grid_width_m = 0.5
to_light_speed = 10000

[simulation_type]
simulation_type = 'electric_static_pic'

[continuaus]
load_continuaus_data = 0
load_directory = 'SNAPSHOT0'
save_continuaus_data = 1
save_directory = 'SNAPSHOT1'

[system]
nx = 8
ny = 4
nz = 16
dt = 0.1
nstep = 100
nmacro_particles_per_grid = [20, 20, 20]
particle_buffer_size = [2.0, 2.0, 2.0] # size(pbuf) >= sum(nparticles_per_grid(:)*particle_buffer_size(:))
imbalance_tolerance_percentage = 10

[system.method]
particle_mover = 'boris'

[system.mpi]
nnodes = [2, 1, 2]

[system.outer_boundary]
boundary_communication = ['periodic', 'periodic', 'no_periodic']
boundary_type_for_electromagnetic_field = ['periodic', 'periodic', 'neumman']
boundary_type_for_particle = [
  ['periodic', 'periodic', 'vanish'],
  ['periodic', 'periodic', 'vanish'],
  ['periodic', 'periodic', 'vanish'],
]

[output]
[output.stdout]
stdout_interval_step = 10

[output.snapshot]
output_start_step = 0
field_output_interval = 100000
current_output_interval = 100000

[plasma]
nspecies = 3
charge_to_mass_ratio = [-1.0, 0.000544617021778308, -1.0]
plasma_frequency = [2.10390362104881, 0.04909886429062906, 2.10390362104881]
thermal_velocity_para = [44.237443494336965, 1.032370595764297, 20.749200214013655]
thermal_velocity_perp = [44.237443494336965, 1.032370595764297, 20.749200214013655]
flow_velocity = [-13.342563807926082, -13.342563807926082]
flow_angle_deg_z = [0.0, 0.0, 0.0]
flow_angle_deg_xy = [180.0, 180.0, 0.0]
cyclotron_frequency = 0.0

[plasma.initialization]
plasma_initialization = ['random-uniform', 'random-uniform', 'none']

[plasma.injection]
nemission_types = 2
outer_boundary = ['none', 'none', 'none', 'none', 'none', 'none']

[plasma.injection.emission1]
emission_type = 'raycast'
current_density = 829.3982816842599
ray_angle_deg_xy = 0
ray_angle_deg_z = 0
ispec = 3
range = [0, 11, 0, 32, 60, 60]

[plasma.injection.emission2]
emission_type = 'plane'
emission_ispec = 3
current_density = 829.3982816842599
emission_angle_deg_xy = 0
emission_angle_deg_z = 0
emission_ranges = [
  [0, 11, 0, 32, 60, 60],
  [11, 21, 0, 11, 60, 60],
  [21, 32, 0, 32, 60, 60],
  [11, 21, 21, 32, 60, 60],
  [11, 21, 11, 21, 60, 60],
]

[object]
object_type = "ellipsoid-hole"
hole_shape = [11, 21, 11, 21, 20, 60]
dent_ratio = 0.5
is_conductor = false

nappend_boundaries = 1

[object.object1]
object_type = "cuboid"
hole_shape = [11, 21, 11, 21, 60, 63]
is_conductor = false
