create_mpi_fft_solver – ohhelp-pic-3d
create_mpi_fft_solver Function
MIT
15 statements
Source File
public function create_mpi_fft_solver(fft_solver_name, fft_boundary_types, local_block, global_block, myid, nprocs, comm, tag) result(obj)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fft_solver_name
integer, intent(in) :: fft_boundary_types(3)
type(t_Block), intent(in) :: local_block
type(t_Block), intent(in) :: global_block
integer, intent(in) :: myid
integer, intent(in) :: nprocs
integer, intent(in) :: comm
integer, intent(in) :: tag
Return Value class(t_MPIFFTSolver3d), allocatable
Calls
Called by
Call graph
create_mpi_fft_solver calls new_mpifftw3solver3d
new_mpifftw3solver3d calls fftw_alloc_real, fftw_mpi_init, fftw_mpi_local_size_3d, fftw_mpi_plan_r2r_3d, new_mpiblockrebaser, logical_end, logical_start, pids, new_block
new_poissonfieldsolver calls create_mpi_fft_solver
pic calls new_poissonfieldsolver
main calls pic