new_HDF5File – ohhelp-pic-3d
new_HDF5File Function
MIT
21 statements
Source File
public function new_HDF5File(filename, mode, comm) result(obj)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
File name to create or open
character(len=1), intent(in) :: mode
Access mode (r: readonly, w: writeonly, a: read/write)
integer, intent(in) :: comm
MPI communicator
Return Value type(t_HDF5File)
Calls
Called by
Contents
Call graph
new_hdf5file calls h5fcreate_f, h5fopen_f, h5pclose_f, h5pcreate_f, h5pset_fapl_mpio_f
new_hdf5forohfield calls new_hdf5file
pic calls new_hdf5forohfield
main calls pic