new_Block – ohhelp-pic-3d
new_Block Function
MIT
8 statements
Source File
public function new_Block(start, end) result(obj)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: start(3)
integer, intent(in) :: end(3)
Return Value type(t_Block)
Called by
Call graph
new_mpifftw3solver3d calls new_block
pic calls new_block, new_poissonfieldsolver
create_mpi_fft_solver calls new_mpifftw3solver3d
main calls pic
new_poissonfieldsolver calls create_mpi_fft_solver