new_Parameters – ohhelp-pic-3d
new_Parameters Function
MIT
46 statements
Source File
public function new_Parameters(toml_filepath) result(obj)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: toml_filepath
Return Value type(t_Parameters)
Calls
Called by
Call graph
new_parameters calls load, require_double, require_double_array, require_int, require_int_array, require_string1, require_string2, require_string3, require_string_array, require_string_array2d, qm, wp
pic calls new_parameters
main calls pic