new_ParticleInjectorManager – ohhelp-pic-3d
new_ParticleInjectorManager Function
MIT
31 statements
Source File
public function new_ParticleInjectorManager(parameters, random_generator) result(obj)
Arguments
Type Intent Optional Attributes Name
class(t_Parameters), intent(inout) :: parameters
class(t_RandomGenerator), intent(in), pointer :: random_generator
Return Value type(t_ParticleInjectorManager)
Calls
Contents
Variables
init_type ispec
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: init_type
integer, public :: ispec
Call graph
new_particleinjectormanager calls injectors_for_initialization, injectors_for_injection, plasma_initialization, new_noparticleinjector, new_novelocitydistribution3d, new_particleinjectorwithdistribution, new_positionrandomuniformdistribution1d, new_simplepositiondistribution3d