new_Hdf5ForOhfield – ohhelp-pic-3d
new_Hdf5ForOhfield Function
MIT
14 statements
Source File
public function new_Hdf5ForOhfield(filename, group_name, global_shape, global_offset, comm) result(obj)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: group_name
integer(kind=8), intent(in) :: global_shape(3)
integer(kind=8), intent(in) :: global_offset(3)
integer, intent(in) :: comm
Return Value type(t_Hdf5ForOhfield)
Calls
Called by
Call graph
new_hdf5forohfield calls create_group, new_hdf5file
new_hdf5file calls h5fcreate_f, h5fopen_f, h5pclose_f, h5pcreate_f, h5pset_fapl_mpio_f
pic calls new_hdf5forohfield
main calls pic