new_PoissonFieldSolver – ohhelp-pic-3d
new_PoissonFieldSolver Function
MIT
34 statements
Source File
public function new_PoissonFieldSolver(local_block, global_block, fft_solver_name, boundary_types, boundary_values, myid, nprocs, comm, tag) result(obj)
Arguments
Type Intent Optional Attributes Name
type(t_Block), intent(in) :: local_block
type(t_Block), intent(in) :: global_block
character(len=*), intent(in) :: fft_solver_name
type(t_StringHolder), intent(in) :: boundary_types(3)
double precision, intent(in), optional :: boundary_values(2,3)
integer, intent(in) :: myid
integer, intent(in) :: nprocs
integer, intent(in) :: comm
integer, intent(in) :: tag
Return Value type(t_PoissonFieldSolver)
Calls
Called by
Call graph
new_poissonfieldsolver calls fft_boundary_types, create_mpi_fft_solver, new_poissonsolver3d
create_mpi_fft_solver calls new_mpifftw3solver3d
new_mpifftw3solver3d calls fftw_alloc_real, fftw_mpi_init, fftw_mpi_local_size_3d, fftw_mpi_plan_r2r_3d, new_mpiblockrebaser, logical_end, logical_start, pids, new_block
pic calls new_poissonfieldsolver
main calls pic