new_MPIFFTW3Solver3d – ohhelp-pic-3d
new_MPIFFTW3Solver3d Function
MIT
62 statements
Source File
public function new_MPIFFTW3Solver3d(fft_boundary_types, local_block, global_block, myid, nprocs, communicator, tag) result(obj)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fft_boundary_types(3)
type(t_Block), intent(in) :: local_block
Block that the local process has. global index 座標系は1:nx
type(t_Block), intent(in) :: global_block
integer, intent(in) :: myid
integer, intent(in) :: nprocs
integer, intent(in) :: communicator
integer, intent(in) :: tag
Return Value type(t_MPIFFTW3Solver3d)
Calls
Called by
Call graph
new_mpifftw3solver3d calls fftw_alloc_real, fftw_mpi_init, fftw_mpi_local_size_3d, fftw_mpi_plan_r2r_3d, new_mpiblockrebaser, logical_end, logical_start, pids, new_block
create_mpi_fft_solver calls new_mpifftw3solver3d
new_poissonfieldsolver calls create_mpi_fft_solver
pic calls new_poissonfieldsolver
main calls pic