new_MPIBlockRebaser – ohhelp-pic-3d
new_MPIBlockRebaser Interface
MIT
4 statements
Source File
public interface new_MPIBlockRebaser
Called by
Module Procedures
private function new_MPIBlockRebaser_with_blocks(local_blocks, require_blocks, pids, ipid, comm) result(obj)
Arguments
Type Intent Optional Attributes Name
type(t_BlockList), intent(in) :: local_blocks
Blocks that each process has.
type(t_BlockList), intent(in) :: require_blocks
Blocks that each process requires.
integer, intent(in) :: pids(:)
Array of process ID (= rank = 0, 1, 2, ..., nproc-1). It should be the same as the order of blocks and require_blocks.
integer, intent(in) :: ipid
Index to identify the current process ID from pids(1:len(pids)).
integer(kind=kind(MPI_COMM_WORLD)), intent(in) :: comm
MPI Communicator.
Return Value type(t_MPIBlockRebaser)
private function new_MPIBlockRebaser_with_local_block(local_block, require_block, pids, ipid, comm, tag) result(obj)
Arguments
Type Intent Optional Attributes Name
type(t_Block), intent(in) :: local_block
Blocks that each process has.
type(t_Block), intent(in) :: require_block
Blocks that each process requires.
integer, intent(in) :: pids(:)
Array of process ID (= rank = 0, 1, 2, ..., nproc-1). It should be the same as the order of blocks and require_blocks.
integer, intent(in) :: ipid
Index to identify the current process ID from pids(1:len(pids)).
integer(kind=kind(MPI_COMM_WORLD)), intent(in) :: comm
MPI Communicator.
integer, intent(in), optional :: tag
Return Value type(t_MPIBlockRebaser)
Call graph
new_mpifftw3solver3d calls new_mpiblockrebaser
create_mpi_fft_solver calls new_mpifftw3solver3d
new_poissonfieldsolver calls create_mpi_fft_solver
pic calls new_poissonfieldsolver
main calls pic