main – ohhelp-pic-3d
main Program
MIT
7 statements
Source File
Uses
ohhelppic3d
mpi
Calls
Variables
Type Attributes Name Initial
character(len=*), parameter :: filename = 'example1.h5'
Source Code
program main
    use mpi
    use ohhelppic3d
    implicit none
    character(*), parameter :: filename = 'example1.h5'
    call pic
end program main
Call graph
main calls pic
pic calls advance, boundary_conditions, create_field, create_particle_mover, eb_interped, fft_boundary_types, interp, move, mpi_abort, mpi_barrier, mpi_comm_rank, mpi_comm_size, mpi_finalize, mpi_init, apply, correct_load_balancing, correct_particle, end_index, exchange_borders, initialize, is_primary_mode, is_secondary_mode, reduce_field, start_index, ohfields, pbuf_size, hdf5_finalize, hdf5_initialize, new_block, new_hdf5forohfield, new_linearinterpolator, new_linearscatter, new_ohfieldfactory, new_ohhelp, new_ohparticles, new_parameters, new_particleboundaries, new_particleinjectormanager, new_particlemoverfactory, new_pcggenerator, new_poissonfieldsolver, particleinjectormanager_initialize_particles, particleinjectormanager_inject_particles, scatter, solve, str
hdf5_finalize calls h5close_f
hdf5_initialize calls h5eset_auto_f, h5open_f
new_hdf5forohfield calls create_group, new_hdf5file
new_parameters calls load, require_double, require_double_array, require_int, require_int_array, require_string1, require_string2, require_string3, require_string_array, require_string_array2d, qm, wp
new_particleboundaries calls new_periodicparticleboundary
new_particleinjectormanager calls require_int, new_noparticleinjector, new_novelocitydistribution3d, new_particleinjectorwithdistribution, new_positionrandomuniformdistribution1d, new_simplepositiondistribution3d
new_pcggenerator calls pcg32_srandom_r
new_poissonfieldsolver calls fft_boundary_types, create_mpi_fft_solver, new_poissonsolver3d
particleinjectormanager_initialize_particles calls inject_particles
create_mpi_fft_solver calls new_mpifftw3solver3d
new_hdf5file calls h5fcreate_f, h5fopen_f, h5pclose_f, h5pcreate_f, h5pset_fapl_mpio_f
new_mpifftw3solver3d calls new_block, fftw_alloc_real, fftw_mpi_init, fftw_mpi_local_size_3d, fftw_mpi_plan_r2r_3d, new_mpiblockrebaser, logical_end, logical_start, pids